import argparse
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description='Generate falling notes piano video from MusicXML or MIDI'
    )
    # Web server mode (mutually exclusive with input file)
    parser.add_argument('input', nargs='?', default=None, help='MusicXML or MIDI file path (.musicxml, .mxl, .xml, .mid, .midi)')
    parser.add_argument('-o', '--output', default=None, help='Output MP4 path (default: <input_name>.mp4)')
    parser.add_argument('--config', default=None, help='YAML config file path')
    parser.add_argument('--width', type=int, default=None)
    parser.add_argument('--height', type=int, default=None)
    parser.add_argument('--fps', type=int, default=None)
    parser.add_argument('--crf', type=int, default=None)
    parser.add_argument('--lookahead', type=float, default=None, dest='lookahead_seconds')
    parser.add_argument('--color-mode', default=None, choices=['single', 'rainbow', 'neon', 'part', 'key_type'])
    parser.add_argument('--note-color', default=None, help='Note color in single mode (hex, e.g. #00D2D2)')
    parser.add_argument('--white-key-color', default=None, help='White key note color in key_type mode (hex, e.g. #00FF80)')
    parser.add_argument('--black-key-color', default=None, help='Black key note color in key_type mode (hex, e.g. #0080FF)')
    parser.add_argument('--no-water-splash', action='store_true', help='Disable water splash effect')
    parser.add_argument('--no-guide-lines', action='store_true', help='Disable guide lines')
    parser.add_argument('--theme', default=None, choices=['auto', 'classic', 'midnight', 'sunset', 'ocean', 'neon', 'pastel'])
    parser.add_argument('--background', default=None, help='Custom background color hex (e.g. #0F0F14)')
    parser.add_argument('--glitter', action='store_true', help='Enable twinkling glitter on note bars')
    parser.add_argument('--no-glow', action='store_true', help='Disable glow effects')
    parser.add_argument('--no-comet', action='store_true', help='Disable comet effect')
    parser.add_argument('--no-energy-color', action='store_true', help='Disable energy-based color')
    parser.add_argument('--energy-mid', type=float, default=None, dest='energy_mid_threshold', help='Energy color low→mid threshold (default: 0.60)')
    parser.add_argument('--energy-high', type=float, default=None, dest='energy_high_threshold', help='Energy color mid→high threshold (default: 0.90)')
    parser.add_argument('--no-starflow', action='store_true', help='Disable ambient starflow effect')
    parser.add_argument('--no-audio', action='store_true', help='Disable audio generation')
    parser.add_argument('--audio-file', default=None, help='External audio file path (skip synthesis)')
    parser.add_argument('--soundfont', default=None, help='Custom soundfont path (.sf2/.sf3)')
    parser.add_argument('--reverb', action='store_true', help='Enable fluidsynth reverb')
    parser.add_argument('--vertical', action='store_true', help='Vertical (portrait) video mode')
    parser.add_argument('--background-image', default=None, help='Background image path (.jpg/.png/.webp)')
    parser.add_argument('--velocity-effect', action='store_true', help='Velocity-based note brightness scaling')
    parser.add_argument('--pedal', action='store_true', help='Sustain pedal visualization')
    parser.add_argument('--key-depression', action='store_true', help='Visual key press depression effect')
    parser.add_argument('--comet-trail-glow', action='store_true', help='Lingering glow trail behind comets')
    parser.add_argument('--glow-intensity', type=float, default=None)
    # Web server options
    parser.add_argument('--web', action='store_true', help='Start web UI server')
    parser.add_argument('--port', type=int, default=5000, help='Port for web server (default: 5000)')
    parser.add_argument('--host', default='127.0.0.1', help='Host for web server (default: 127.0.0.1)')
    return parser.parse_args()
